const { cmd } = require('../command');

cmd({
    pattern: "requestunban",
    desc: "Generate a WhatsApp unban request message",
    category: "tools",
    filename: __filename
}, async (conn, m, store, { from, reply }) => {
    try {
        // Random polite appeal messages
        const appeals = [
            "Hello WhatsApp Support,\n\nMy account was recently banned. I believe this was a mistake as I have always complied with WhatsApp's Terms of Service. Please review my case and restore my access.\n\nThank you.",
            "Dear WhatsApp Team,\n\nI woke up to find my account banned. I use WhatsApp only for personal communication with friends and family. Kindly reconsider and unban my number.\n\nRegards.",
            "Hi,\n\nMy WhatsApp number has been banned unexpectedly. I believe this is an error as I have not violated any rules. Please help me regain access.\n\nSincerely."
        ];

        // Pick a random one
        const randomAppeal = appeals[Math.floor(Math.random() * appeals.length)];

        // Random fake ticket number
        const ticketNumber = `#${Math.floor(100000 + Math.random() * 900000)}`;

        // Full message
        const unbanMessage = `📩 *WhatsApp Unban Request*\n\nTicket: ${ticketNumber}\n\n${randomAppeal}\n\n📌 *Copy this message and send it to:* wa.me/14155238886\n\n⚠️ This is a template. Modify with your own details for best results.`;

        // Fake verified vCard quote
        const quotedContact = {
            key: { fromMe: false, participant: "0@s.whatsapp.net", remoteJid: "status@broadcast" },
            message: {
                contactMessage: {
                    displayName: "WhatsApp Support",
                    vcard: `BEGIN:VCARD\nVERSION:3.0\nFN:WhatsApp Support\nORG:WhatsApp\nTEL;type=CELL;type=VOICE;waid=14155238886:+1 415-523-8886\nEND:VCARD`
                }
            }
        };

        // Send message
        await conn.sendMessage(from, {
            text: unbanMessage,
            contextInfo: {
                mentionedJid: [m.sender],
                forwardedNewsletterMessageInfo: {
                    newsletterJid: "120363297812093636@newsletter",
                    newsletterName: "PK-XMD Bot Updates",
                    serverMessageId: -1
                },
                externalAdReply: {
                    title: "WhatsApp Unban Helper",
                    body: "Template generated by PK-XMD",
                    thumbnailUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg",
                    sourceUrl: "https://www.whatsapp.com/contact",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        }, { quoted: quotedContact });

    } catch (e) {
        console.error(e);
        reply("❌ Failed to generate unban request template.");
    }
});
                    
